        <title>Главная</title>
        <hr>

        <div class="row">
            <div class="col-lg-12">
                <div class="well text-center">
                    <h1>Ебануцца какой портал</h1>
                    Первый совершенно бесплатный ресурс по изучению английского языка
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <h2>Можа первая статья</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin auctor quam ac tempor. Cras a ante sed libero mollis sodales. Praesent fringilla, neque ut ultrices faucibus, dolor eros ultrices neque, nec bibendum arcu ipsum eget justo.</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
            <div class="col-lg-4">
                <h2>Можа другая статья</h2>
                <p>Phasellus vestibulum sagittis purus laoreet varius. Pellentesque malesuada malesuada mattis. Aliquam sed porta nisi, eget suscipit dolor. Nam ipsum sapien, rhoncus eu leo eu, ultricies pellentesque tellus.</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
            <div class="col-lg-4">
                <h2>Можа трэцяя статья</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin auctor quam ac tempor. Cras a ante sed libero mollis sodales. Praesent fringilla, neque ut ultrices faucibus, dolor eros ultrices neque, nec bibendum arcu ipsum eget justo.</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
        </div>