<title>Авторизация</title>
<div class="page-header">
    <h1>Авторизация</h1>
</div >
        <div class="row">
            <div class="col-lg-12">
                <div class="well">
                    <div class="row">
                    <div class="col-lg-8">
                        <p>Оу вачигос! Тумороу  оу вачигос бэбэ еээ!</p>
                    </div>
                    </div>    
                </div>
            </div>
        </div>
<div class="container">
    <div class="row">
     <?
      $form = $this->form;
      $form->prepare();
      $form->setAttribute('action', $this->url('auth'));
      $form->setAttribute('method', 'post');
      ?>
     <div class='col-lg-2'>
      <?   
      echo $this->form()->openTag($form);
      $login = $form->get('login');

      echo $this->formInput($login)."\n</br>";
      echo $this->formElementErrors($login);
      ?>
     </div>
      <div class='col-lg-2'>
      <?
      $pass = $form->get('pass');
      echo $this->formInput($pass)."\n</br>";
      echo $this->formElementErrors($pass);
      ?>
      </div>
      <?
      echo $this->formInput($form->get('submit'));
      echo $this->form()->closeTag()
     ?>
    </div>
</div>
