<title>Регистрация</title>
<div class="page-header">
    <h1>Регистрация</h1>
</div >
        <div class="row">
            <div class="col-lg-12">
                <div class="well">
                    <div class="row">
                    <div class="col-lg-8">
                        <p>Оу вачигос! Тумороу  оу вачигосб бэбэ еээ!</p>
                    </div>
                    </div>    
                </div>
            </div>
        </div>
<div class="container">
    <div class="row">
     <?
      $form = $this->form;
      $form->prepare();
      $form->setAttribute('action', $this->url('registration'));
      ?>
      <div class="row">
      <?= $this->form()->openTag($form); ?>
      <div class="row"><div class="col-lg-3">
      <?
      $name = $form->get('full_name');
      echo $this->formInput($name);
      echo $this->formElementErrors($name);
      ?>
      </div></div></br>
      <div class="row"><div class="col-lg-3">
      <? 
      $surname = $form->get('surname');
      echo $this->formInput($surname);
      echo $this->formElementErrors($surname);
      ?>
      </div></div></br>
      <div class="row"><div class="col-lg-3">
      <? 
      $login = $form->get('login');
      echo $this->formInput($login);
      echo $this->formElementErrors($login);
      ?>
      </div></div></br>
      <div class="row"><div class="col-lg-3">
      <?
      $pass = $form->get('pass');
      echo $this->formInput($pass); 
      echo $this->formElementErrors($pass);
      ?>
      </div></div></br>
      <div class="row"><div class="col-lg-3">
      <?
      $passReenter = $form->get('pass_re_enter');
      echo $this->formInput($passReenter); 
      echo $this->formElementErrors($passReenter);
      ?>
      </div></div></br>
      <div class="row"><div class="col-lg-3">
      <?
      $captcha = $form->get('captcha');
      echo $this->formCaptcha($captcha);
      echo $this->formElementErrors($captcha);
      ?>
      </div></div></br>
      <div class="row"><div class="col-lg-3">
      <?= $this->formInput($form->get('submit')); ?>
      </div></div></br>
      <? $this->form()->closeTag($form); ?>
      </div>


      

    </div>
</div>
