<title>Регистрация</title>
<div class="page-header">
    <h1>Регистрация</h1>
</div >
        <div class="row">
            <div class="col-lg-12">
                <div class="well">
                    <div class="row">
                    <div class="col-lg-8">
                        <p>Оу вачигос! Тумороу  оу вачигосб бэбэ еээ!</p>
                    </div>
                    </div>    
                </div>
            </div>
        </div>
<div class="container">
    <div class="row">
     <?
      $form = $this->form;
      $form->setAttribute('action', $this->url('index'));
      $form->prepare();
      echo '<div class="row">';
      echo $this->form()->openTag($form);
      echo '<div class="row"><div class="col-lg-3">';
      echo $this->formInput($form->get('name'));
      echo '</div></div></br>';
      echo '<div class="row"><div class="col-lg-3">';
      echo $this->formInput($form->get('surname'));
      echo '</div></div></br>';
      echo '<div class="row"><div class="col-lg-3">';
      echo $this->formInput($form->get('login'));
      echo '</div></div></br>';
      echo '<div class="row"><div class="col-lg-3">';
      echo $this->formInput($form->get('pass'));
      echo '</div></div></br>';
      echo '<div class="row"><div class="col-lg-3">';
      echo $this->formInput($form->get('pass_re_enter'));
      echo '</div></div></br>';
      echo '<div class="row"><div class="col-lg-3">';
      echo $this->formInput($form->get('submit'));
      echo '</div></div></br>';
      echo $this->form()->closeTag($form);
      echo '</div>';

     ?>
    </div>
</div>
