<title>Успешная регистрация</title>
<div class="page-header">
    <h1>Успешная регистрация</h1>
</div >
<div class="row">
    <div class="col-lg-12">
        <div class="well">
            <div class="row">
            <div class="col-lg-8">
                <p>Вы успешно зарегистрировались!</p>
                <p>Используйте введенный email и пароль для авторизации.</p>
            </div>
            </div>    
        </div>
    </div>
</div>