<title>Авторизация</title>
<div class="page-header">
    <h1>Авторизация</h1>
</div >
<div class="row">
    <div class="col-lg-12">
        <div class="well">
            <div class="row">
            <div class="col-lg-8">
                <p>Авторизируйтесь используя ваш Email и пароль!</p>
            </div>
            </div>    
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <p class="text-danger"><?= $this->authError ?></p>
        </div>
    </div>    
    <div class="row">
     <?php
      $form = $this->form;
      $form->prepare();
      $form->setAttribute('action', $this->url('auth'));
      $form->setAttribute('method', 'post');
      ?>
     <div class='col-lg-2'>
      <?php   
      echo $this->form()->openTag($form);
      $email = $form->get('login');

      echo $this->formInput($email)."\n</br>";
      echo $this->formElementErrors($email);
      ?>
     </div>
      <div class='col-lg-2'>
      <?php
      $pass = $form->get('pass');
      echo $this->formInput($pass)."\n</br>";
      echo $this->formElementErrors($pass);
      ?>
      </div>
      <?php
      echo $this->formInput($form->get('submit'));
      echo $this->form()->closeTag()
     ?>
    </div>
</div>
