<title>Публикации</title>
<div class="page-header">
    <h1>Статья номер раз</h1>
</div >
        <div class="row">
            <div class="col-lg-12">
                <div class="well">
                    <div class="row">
                    <div class="col-lg-8">
                        <p>Краткое описание ебануцца какой первой статьи</p>
                    </div>
                    </div>    
                </div>
            </div>
        </div>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <?= $this->content?>
        </div>
        <div class=col-lg-1"">
            <?php 
               echo $this->widget;
            ?>
        </div>
    </div>
</div>
