<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="/img/logo.ico" type="image/png">

    <!-- Bootstrap core CSS -->
    <!--<link href="/css/bootstrap.css" rel="stylesheet">-->
    <?php
       echo $this->HeadScript()->appendFile("/js/jquery-1.10.2.js", $type="text/javascript")
                               ->appendFile("/js/bootstrap.js", $type="text/javascript");
       echo $this->HeadLink()->appendStylesheet("/css/bootstrap.css")
                             ->appendStylesheet("/css/small-business.css");
    ?>

    <!-- Add custom CSS here -->
    <!--<link href="/css/small-business.css" rel="stylesheet">-->

</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                <a class="navbar-brand logo-nav" href="/">
                    <img src="/img/logo.jpg" title="Старадаўняй ліцвінскай пагоні не разбіць, не спыніць, не стрымаць!">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    
                    <?php $auth = new Zend\Authentication\AuthenticationService();
                     if(!$auth->hasIdentity()){
                    ?>
                    <li><a href="<?= $this->url('auth', array('action' => 'login')) ?>">Войти</a>
                    </li>
                    <li><a href="<?= $this->url('registration', array('action'=>'index'))?>">Регистрация</a>
                    </li>
                     <?php }else{ ?>
                    <li><a href="<?= $this->url('auth') ?>logout">Выйти</a>
                    </li>
                     <?php } ?>
                    
                </ul>
                
            </div>

            
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
        
    </nav>

    <div class="container">
        <?php if($auth->hasIdentity()){ ?>
        <?php $user = $auth->getIdentity();?>
            <div class="row">
                <div class="col-lg-12">
                    <div class="well">
                        <div class="row">
                        <div class="col-lg-8">
                            <p>Здравствуйте, <?= $user ?></p>
                        </div>
                        </div>    
                    </div>
                </div>
            </div>
        <?php } ?>
            <?php echo $this->content; ?>


        <footer>
            <hr>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; av.by test task 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

</body>

</html>