<title>Добавление статьи</title>
<hr>
        <div class="row">
            <div class="col-lg-12">
                <div class="well text-center">
                    <h1>Добавление статьи</h1>
                </div>
            </div>
        </div>
<div class="container ">
 <?php
      $form = $this->form;
      $form->prepare();
      $form->setAttribute('action', 'add-post');
      $form->setAttribute('method', 'post');
      ?>
    <?php echo $this->form()->openTag($form)?>
    <div class="row">
        <div class="col-lg-3">
            <?php
            $title = $form->get('title');
            echo $this->formInput($title);
            echo $this->formElementErrors($title);
            ?>
        </div>
    </div></br>
    <div class="row">
        <div class="col-lg-3">
            <?php
             $body = $form->get('body');
             echo $this->formTextarea($body);
             echo $this->formElementErrors($body);
            ?>
        </div>
    </div></br>
    <div class="row">
        <div class="col-lg-3">
            <?php
             $submit = $form->get('submit');
             echo $this->formSubmit($submit);
            ?>
        </div>
    </div></br>
    <?php echo $this->form()->closeTag($form)?>
    
</div>