<title>Правка статьи</title>
<hr>
        <div class="row">
            <div class="col-lg-12">
                <div class="well text-center">
                    <h1>Правка статьи</h1>
                </div>
            </div>
        </div>
<div class="container ">
 <?php
      $form = $this->form;
      $form->prepare();
      $form->setAttribute('action', 'edit-post');
      $form->setAttribute('method', 'post');
      ?>
    <?= $this->form()->openTag($form)?>
    <?php
      $id = $form->get('id');
      echo $this->formHidden($id);
    ?>
    <div class="row">
        <div class="col-lg-4">
            <?php
            $title = $form->get('title');
            echo $this->formInput($title);
            ?>
        </div>
    </div></br>
    <div class="row">
        <div class="col-lg-6">
            <?php
             $body = $form->get('text');
             $body->setAttribute('rows', '10');
             $body->setAttribute('cols', '100');
             echo $this->formTextarea($body);
            ?>
        </div>
    </div></br>
    <div class="row">
        <div class="col-lg-3">
            <?php
             $submit = $form->get('submit');
             echo $this->formSubmit($submit);
            ?>
        </div>
    </div></br>
    <?= $this->form()->closeTag($form)?>
    
</div>