<title>Статьи</title>
<?php 
$title = 'Статьи';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?= $this->url('blogPost') ?>/add-post">Добавить статью</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Author</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($posts as $post) : ?>
 <tr>
     <td><a href="<?= $this->url('blogPost') ?>/view-post/<?= $post->id ?>"><?= $post->title ?></a></td>
     <td><?php echo $this->escapeHtml($post->author_id);?></td>
     <td>
         <a href="<?= $this->url('blogPost');?>/edit-post/<?= $post->id;?>">Edit</a>
         <a href="<?php echo $this->url('blogPost')?>/remove-post/<?= $post->id?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>